/*
Copyright (C) 2017 Julian Andres Klode <jak@jak-linux.org>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package importer

import (
	"encoding/xml"
	"github.com/shopspring/decimal"

	"fmt"
	"os"
)

// portfolio performance xml impoorter

type PortfolioClient struct {
	XMLName    xml.Name    `xml:"client"`
	Portfolios []Portfolio `xml:"portfolios>portfolio"`
}

type Portfolio struct {
	Name         string                 `xml:"name"`
	XMLName      xml.Name               `xml:"portfolio"`
	Transactions []PortfolioTransaction `xml:"transactions>portfolio-transaction"`
}
type PortfolioTransaction struct {
	XMLName xml.Name        `xml:"portfolio-transaction"`
	Amount  decimal.Decimal `xml:"amount"`
	Date    string          `xml:"date"`
	Shares  decimal.Decimal `xml:"shares"`
}

// LBBParseFile parses a CSV file generated by the Landesbank Berlin for their
// Amazon credit cards.
func PortfolioParse(path string) (*PortfolioClient, error) {
	var client PortfolioClient
	r, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() {
		r.Close()
	}()
	err = xml.NewDecoder(r).Decode(&client)
	if err != nil {
		fmt.Printf("%s", err)
		return nil, err
	}
	return &client, nil
}
